pub mod diffusion_animation;
pub mod emit_color_animation;
pub mod emit_speed_animation;
pub mod emitter;
pub mod emitter_animation;
pub mod emitter_animation_handler;
pub mod loose_movement_animation;
pub mod randomize_size_animation;
pub mod sway_animation;
